using System.Collections.Generic;
using System.Linq;
using TranslateClient.Common;

namespace TranslateClient.Google
{
    public class GoogleLanguageMap
    {
        public readonly List<Language> Languages = new List<Language>()
        {
            new Language("auto", "Automatic"),
            new Language("af", "Afrikaans"),
            new Language("sq", "Albanian"),
            new Language("am", "Amharic"),
            new Language("ar", "Arabic"),
            new Language("hy", "Armenian"),
            new Language("az", "Azerbaijani"),
            new Language("eu", "Basque"),
            new Language("be", "Belarusian"),
            new Language("bn", "Bengali"),
            new Language("bs", "Bosnian"),
            new Language("bg", "Bulgarian"),
            new Language("ca", "Catalan"),
            new Language("ceb", "Cebuano"),
            new Language("ny", "Chichewa"),
            new Language("zh-cn", "Chinese Simplified"),
            new Language("zh-tw", "Chinese Traditional"),
            new Language("co", "Corsican"),
            new Language("hr", "Croatian"),
            new Language("cs", "Czech"),
            new Language("da", "Danish"),
            new Language("nl", "Dutch"),
            new Language("en", "English"),
            new Language("eo", "Esperanto"),
            new Language("et", "Estonian"),
            new Language("tl", "Filipino"),
            new Language("fi", "Finnish"),
            new Language("fr", "French"),
            new Language("fy", "Frisian"),
            new Language("gl", "Galician"),
            new Language("ka", "Georgian"),
            new Language("de", "German"),
            new Language("el", "Greek"),
            new Language("gu", "Gujarati"),
            new Language("ht", "Haitian Creole"),
            new Language("ha", "Hausa"),
            new Language("haw", "Hawaiian"),
            new Language("iw", "Hebrew"),
            new Language("hi", "Hindi"),
            new Language("hmn", "Hmong"),
            new Language("hu", "Hungarian"),
            new Language("is", "Icelandic"),
            new Language("ig", "Igbo"),
            new Language("id", "Indonesian"),
            new Language("ga", "Irish"),
            new Language("it", "Italian"),
            new Language("ja", "Japanese"),
            new Language("jw", "Javanese"),
            new Language("kn", "Kannada"),
            new Language("kk", "Kazakh"),
            new Language("km", "Khmer"),
            new Language("ko", "Korean"),
            new Language("ku", "Kurdish (Kurmanji)"),
            new Language("ky", "Kyrgyz"),
            new Language("lo", "Lao"),
            new Language("la", "Latin"),
            new Language("lv", "Latvian"),
            new Language("lt", "Lithuanian"),
            new Language("lb", "Luxembourgish"),
            new Language("mk", "Macedonian"),
            new Language("mg", "Malagasy"),
            new Language("ms", "Malay"),
            new Language("ml", "Malayalam"),
            new Language("mt", "Maltese"),
            new Language("mi", "Maori"),
            new Language("mr", "Marathi"),
            new Language("mn", "Mongolian"),
            new Language("my", "Myanmar (Burmese)"),
            new Language("ne", "Nepali"),
            new Language("no", "Norwegian"),
            new Language("ps", "Pashto"),
            new Language("fa", "Persian"),
            new Language("pl", "Polish"),
            new Language("pt", "Portuguese"),
            new Language("ma", "Punjabi"),
            new Language("ro", "Romanian"),
            new Language("ru", "Russian"),
            new Language("sm", "Samoan"),
            new Language("gd", "Scots Gaelic"),
            new Language("sr", "Serbian"),
            new Language("st", "Sesotho"),
            new Language("sn", "Shona"),
            new Language("sd", "Sindhi"),
            new Language("si", "Sinhala"),
            new Language("sk", "Slovak"),
            new Language("sl", "Slovenian"),
            new Language("so", "Somali"),
            new Language("es", "Spanish"),
            new Language("su", "Sundanese"),
            new Language("sw", "Swahili"),
            new Language("sv", "Swedish"),
            new Language("tg", "Tajik"),
            new Language("ta", "Tamil"),
            new Language("te", "Telugu"),
            new Language("th", "Thai"),
            new Language("tr", "Turkish"),
            new Language("uk", "Ukrainian"),
            new Language("ur", "Urdu"),
            new Language("uz", "Uzbek"),
            new Language("vi", "Vietnamese"),
            new Language("cy", "Welsh"),
            new Language("xh", "Xhosa"),
            new Language("yi", "Yiddish"),
            new Language("yo", "Yoruba"),
            new Language("zu", "Zulu")
        };

        public string GetCode(string language)
        {
            if (string.IsNullOrEmpty(language)) return null;

            var languageLower = language.ToLower();

            return Languages.Where(l => l.Name.ToLower() == languageLower).Select(l => l.Code).FirstOrDefault();
        }
    }
}
